### ISSUE TITLE
Can't serialize MeanImputation if there are no missing values in training data

### ISSUE THREAD

**Issue by remram44** [usc-isi-i2/dsbox-cleaning#29] opened 2018-01-10 21:23 UTC
If there was no missing values in the training data, self.mean_values doesn't get set, and get_params() crashes.

**Comment by luofanghao** [comment] 2018-01-10 22:43
Hi thank you so much for providing the bug info !
I just fixed it at the `master` branch.

**Comment by remram44** [comment] 2018-01-11 03:37
`get_params()` still crashes, now with this:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-1d860598bf42> in <module>()
----> 1 imputer.get_params()

~/Documents/programming/_venvs/d3m/src/dsbox-datacleaning/dsbox/datapreprocessing/cleaner/mean.py in get_params(self)
     88     def get_params(self) -> Params:
     89         if self._is_fitted:
---> 90             return Params(mean_values=self.mean_values)
     91         else:
     92             return Params(mean_values=dict())

~/Documents/programming/_venvs/d3m/src/d3m-metadata/d3m_metadata/params.py in __init__(self, other, **values)
     79         for name, value in values.items():
     80             value_type = self.__params_items__[name]  # type: ignore
---> 81             if not utils.is_instance(value, value_type):
     82                 raise TypeError("Value '{value}' is not an instance of the type: {value_type}".format(value=value, value_type=value_type))
     83 

~/Documents/programming/_venvs/d3m/src/d3m-metadata/d3m_metadata/utils.py in is_instance(obj, cls)
    110     # correctly work with type variables.
    111     # See: https://github.com/Stewori/pytypes/issues/24
--> 112     return type_util._isinstance(obj, cls, bound_typevars={})
    113 
    114 

~/Documents/programming/_venvs/d3m/src/pytypes/pytypes/type_util.py in _isinstance(obj, cls, bound_Generic, bound_typevars)
   1489     if obj == {}:
   1490         try:
-> 1491             return issubclass(typing.Dict, cls.__origin__)
   1492         except TypeError:
   1493             return issubclass(typing.Dict, cls)

AttributeError: type object 'dict' has no attribute '__origin__'
```

**Comment by luofanghao** [comment] 2018-01-11 04:34
I don't have this issue on my environment. Could you provide more code so I can replicate the bug?

By the way, what version of `metadata` you are using?

**Comment by remram44** [comment] 2018-01-11 04:38
I am using the latest stable version, v2018.1.5. There isn't much more code, the primitive has been trained on data with no missing values... mean_values is `{}`.

**Comment by luofanghao** [comment] 2018-01-11 06:10
I updated `metadata` to v2018.1.5 and have tested it with the data with no missing values. It worked.

Could you check whether you are using our latest code on `master` branch?

**Comment by luofanghao** [comment] 2018-01-11 06:11
my tested code are like following, FYI:

```
hp = MeanHyperparameter.sample()
imputer = MeanImputation(hyperparams=hp)
imputer.set_training_data(inputs=imputedData)	# no-missing-value data
imputer.fit(timeout=100)	# give 100 seconds to fit
print (imputer.get_params()) # give results
```

**Comment by remram44** [comment] 2018-01-11 15:43
```python
from d3mds import D3MDS
from dsbox.datapreprocessing.cleaner import MeanImputation, MeanHyperparameter

ds = D3MDS('data/LL0_21_car/LL0_21_car_dataset',
           'data/LL0_21_car/LL0_21_car_problem')
train_data = ds.get_train_data()

hp = MeanHyperparameter.sample()
imputer = MeanImputation(hyperparams=hp)
imputer.set_training_data(inputs=train_data)
imputer.fit(timeout=100)
print (imputer.get_params())  # same crash as above
```
Extract from my environment:
```
-e git+https://gitlab.com/datadrivendiscovery/metadata.git@de9d3dea0fffb1040c423bb1f84b15d15c1476e8#egg=d3m_metadata
-e git+https://github.com/usc-isi-i2/dsbox-cleaning.git@90079d21c75e8aab563d82bd978ccfcbc124eb91#egg=dsbox_datacleaning
dsbox-dataprofiling==0.3.0
fancyimpute==0.3.0
Keras==2.1.2
-e git+https://gitlab.com/datadrivendiscovery/primitive-interfaces.git@d900bbf93747f0dc6fa3f0116a9a041d6a506b43#egg=primitive_interfaces
-e git+https://github.com/Stewori/pytypes.git@3fb6266b5fbdd6913f92357c36ec478f02812644#egg=pytypes
tensorflow==1.4.1
typing==3.6.2
```

**Comment by kyao** [comment] 2018-01-12 18:24
Can you try pulling from branch v1.0 to see if the problem is fixed?

**Comment by luofanghao** [comment] 2018-01-27 23:30
are this issue fixed now?

**Comment by remram44** [comment] 2018-01-29 18:59
Seems to work, thanks!

**Closed as completed** 2018-01-29 18:59 UTC
